/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Cancion;
import de.craften.ui.swingmaterial.MaterialColor;
import java.awt.Frame;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JProgressBar;
import javazoom.jlgui.basicplayer.BasicController;
import javazoom.jlgui.basicplayer.BasicPlayerEvent;
import javazoom.jlgui.basicplayer.BasicPlayerException;
import javazoom.jlgui.basicplayer.BasicPlayerListener;
import mdlaf.MaterialColors;
import mdlaf.MaterialFonts;
import sun.awt.ModalityEvent;

/**
 *
 * @author gonzalo
 */
public class songChica extends javax.swing.JPanel{
  private String path;
  private Cancion cancion;
  
    /** 
     * Creates new form songChica
     */
    public songChica(Cancion cancion) {
        initComponents();
        this.setBackground(MaterialColor.BLUEGREY_900);
        jPanel1.setBackground(MaterialColor.BLUEGREY_900);
       //jPanel1.setBorder(new DibujarBordes().bordeBandeja());
        jLabel1.setFont(MaterialFonts.THIN);
        jButton3.setBorderPainted(false);
        jButton3.setBorder(new DibujarBordes().borderContentPanel());
        //jButton3.setBackground(MaterialColor.BLUEGREY_800);
        jButton3.setUI( new DibujarBordes().buttonUi2());
        jButton3.setOpaque(false);
        jProgressBar1.setUI(new DibujarBordes().progressBarUI1());
        jButton1.setUI(new DibujarBordes().buttonUi2());
        jButton1.setOpaque(false);
        this.cancion=cancion;
        this.setListener(cancion);
    }
    
    public void setListener(Cancion cancion){
        if(cancion.getActions().getPlayerListener()==null)
        cancion.getActions().setPlayerListener(new PlayerListener(this.jProgressBar1));
        else {
           cancion.getActions().getPlayerListener().setProgressBar(this.jProgressBar1);
        }
        loadIcon();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 100));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dj/Imagenes/play.png"))); // NOI18N
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dj/Imagenes/ecualizador.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      
        if(cancion.getActions().isStopped()||cancion.getActions().isUnknow()){
         cancion.getActions().play(cancion.getDireccion()); //play the file with the path direction
         loadIcon();
        }
        else if(cancion.getActions().isPlaying()){
         cancion.getActions().pause(); //pause the file+
          loadIcon();
        }
        else if(cancion.getActions().isPause()){
         cancion.getActions().resume(); //resume the file
         loadIcon();
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        uiEqualizador equalizer=  new uiEqualizador();
     
        equalizer.setEscucha(cancion.getActions().getPlayerListener());
        equalizer.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    public void setTitle(String title){
    jLabel1.setText(title);
    }
    
    public JLabel getLabel(){
    return jLabel1;
    }
    
    
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables


    
    public void loadIcon(){
         if(cancion.getActions().isStopped()){
            ImageIcon icon=new ImageIcon(getClass().getResource("/dj/Imagenes/play.png"));
         jButton3.setIcon(icon);
        }else if(cancion.getActions().isUnknow()){
             ImageIcon icon=new ImageIcon(getClass().getResource("/dj/Imagenes/play.png"));
         jButton3.setIcon(icon);
        }
        else if(cancion.getActions().isPlaying()){
            ImageIcon icon=new ImageIcon(getClass().getResource("/dj/Imagenes/pausa.png"));
         jButton3.setIcon(icon);
        }
        else if(cancion.getActions().isPause()){
          ImageIcon icon=new ImageIcon(getClass().getResource("/dj/Imagenes/play.png"));
         jButton3.setIcon(icon);
        } 
    }

    public JProgressBar getjProgressBar1() {
        return jProgressBar1;
    }
    
}