/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Funciones.equalizador;
import clases.DibujarBordes;
import clases.PlayerListener;
import de.craften.ui.swingmaterial.MaterialColor;
import java.awt.event.ActionEvent;
import javax.swing.JSlider;

/**
 *
 * @author familia
 */
public class uiEqualizador extends javax.swing.JFrame {

    /**
     * Creates new form uiEqualizador
     */
    PlayerListener escucha;
    JSlider[] eq1;
    equalizador equalAudio;
    
    public uiEqualizador() {
        this.setResizable(false);
        initComponents();
        eq1=new JSlider[10];
        cargarSlider();
        equalAudio=new equalizador();
        jPanel12.setBackground(MaterialColor.BLUEGREY_900);
        cambiarDiseñoSlider();
    }
    public void setEscucha(PlayerListener l)
    {
    escucha=l;
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel12 = new javax.swing.JPanel();
        Parlante = new javax.swing.JSlider();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jLabel7 = new javax.swing.JLabel();
        js0 = new javax.swing.JSlider();
        js5 = new javax.swing.JSlider();
        js4 = new javax.swing.JSlider();
        js6 = new javax.swing.JSlider();
        js8 = new javax.swing.JSlider();
        js1 = new javax.swing.JSlider();
        js3 = new javax.swing.JSlider();
        js2 = new javax.swing.JSlider();
        js9 = new javax.swing.JSlider();
        js7 = new javax.swing.JSlider();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel12.setToolTipText("");
        jPanel12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel12KeyPressed(evt);
            }
        });
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Parlante.setMinimum(-100);
        Parlante.setValue(0);
        Parlante.setFocusable(false);
        Parlante.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ParlanteStateChanged(evt);
            }
        });
        Parlante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ParlanteKeyPressed(evt);
            }
        });
        jPanel12.add(Parlante, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 211, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Izquierda");
        jPanel12.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 211, -1, 26));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Derecha");
        jPanel12.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, -1, 26));

        jSlider1.setMaximum(50);
        jSlider1.setToolTipText("");
        jSlider1.setValue(0);
        jSlider1.setFocusable(false);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        jSlider1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSlider1KeyPressed(evt);
            }
        });
        jPanel12.add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 160, -1, 33));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Pitch");
        jPanel12.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 167, -1, -1));

        js0.setMinimum(-100);
        js0.setOrientation(javax.swing.JSlider.VERTICAL);
        js0.setToolTipText("");
        js0.setValue(0);
        js0.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                js0StateChanged(evt);
            }
        });
        js0.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                js0KeyPressed(evt);
            }
        });
        jPanel12.add(js0, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 20, 100));

        js5.setMinimum(-100);
        js5.setOrientation(javax.swing.JSlider.VERTICAL);
        js5.setToolTipText("");
        js5.setValue(0);
        js5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                js5StateChanged(evt);
            }
        });
        jPanel12.add(js5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 20, 100));

        js4.setMinimum(-100);
        js4.setOrientation(javax.swing.JSlider.VERTICAL);
        js4.setToolTipText("");
        js4.setValue(0);
        js4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                js4StateChanged(evt);
            }
        });
        jPanel12.add(js4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 20, 100));

        js6.setMinimum(-100);
        js6.setOrientation(javax.swing.JSlider.VERTICAL);
        js6.setValue(0);
        js6.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                js6StateChanged(evt);
            }
        });
        jPanel12.add(js6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 20, 100));

        js8.setMinimum(-100);
        js8.setOrientation(javax.swing.JSlider.VERTICAL);
        js8.setValue(0);
        js8.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                js8StateChanged(evt);
            }
        });
        jPanel12.add(js8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 20, 100));

        js1.setMinimum(-100);
        js1.setOrientation(javax.swing.JSlider.VERTICAL);
        js1.setToolTipText("");
        js1.setValue(0);
        js1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                js1StateChanged(evt);
            }
        });
        jPanel12.add(js1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 20, 100));

        js3.setMinimum(-100);
        js3.setOrientation(javax.swing.JSlider.VERTICAL);
        js3.setToolTipText("");
        js3.setValue(0);
        js3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                js3StateChanged(evt);
            }
        });
        jPanel12.add(js3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 20, 100));

        js2.setMinimum(-100);
        js2.setOrientation(javax.swing.JSlider.VERTICAL);
        js2.setValue(0);
        js2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                js2StateChanged(evt);
            }
        });
        jPanel12.add(js2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 20, 100));

        js9.setMinimum(-100);
        js9.setOrientation(javax.swing.JSlider.VERTICAL);
        js9.setToolTipText("");
        js9.setValue(0);
        js9.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                js9StateChanged(evt);
            }
        });
        jPanel12.add(js9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 20, 100));

        js7.setMinimum(-100);
        js7.setOrientation(javax.swing.JSlider.VERTICAL);
        js7.setToolTipText("");
        js7.setValue(0);
        js7.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                js7StateChanged(evt);
            }
        });
        jPanel12.add(js7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 20, 100));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("31");
        jPanel12.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("62");
        jPanel12.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("125");
        jPanel12.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Graves");
        jPanel12.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 70, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Medios");
        jPanel12.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 80, 20));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Agudos");
        jPanel12.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 2, -1, 30));

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("250");
        jPanel12.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("500");
        jPanel12.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("1KHZ");
        jPanel12.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("    2");
        jPanel12.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 30, -1));

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("   4");
        jPanel12.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 30, -1));

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("8 ");
        jPanel12.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 140, 10, -1));

        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("16KHZ");
        jPanel12.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 40, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NORMAL", "CLASSICAL", "CLUB", "DANCE", "FULLBASS", "FULLBASSTREBLE", "FULLTREBLE", "LIVE", "PARTY", "POP", "REGGAE", "ROCK ", "TECHNO " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel12.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ParlanteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ParlanteStateChanged
        double sw = (double) (Parlante.getValue() / 100);//cambio el paneo del programa
    }//GEN-LAST:event_ParlanteStateChanged

    private void ParlanteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ParlanteKeyPressed
      
        setFocusable(true);
    }//GEN-LAST:event_ParlanteKeyPressed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
    }//GEN-LAST:event_jSlider1StateChanged

    private void jSlider1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSlider1KeyPressed
       
        setFocusable(true);
    }//GEN-LAST:event_jSlider1KeyPressed

    private void js0StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_js0StateChanged
        escucha.setEq(0, js0.getValue());
    }//GEN-LAST:event_js0StateChanged

    private void js0KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_js0KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_js0KeyPressed

    private void js5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_js5StateChanged
        escucha.setEq(5, js5.getValue());
    }//GEN-LAST:event_js5StateChanged

    private void js4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_js4StateChanged
        escucha.setEq(4, js4.getValue());
    }//GEN-LAST:event_js4StateChanged

    private void js6StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_js6StateChanged
        escucha.setEq(6, js6.getValue());
    }//GEN-LAST:event_js6StateChanged

    private void js8StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_js8StateChanged
        escucha.setEq(9, js8.getValue());
    }//GEN-LAST:event_js8StateChanged

    private void js1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_js1StateChanged
       escucha.setEq(1, js1.getValue());
    }//GEN-LAST:event_js1StateChanged

    private void js3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_js3StateChanged
        escucha.setEq(3, js3.getValue());
    }//GEN-LAST:event_js3StateChanged

    private void js2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_js2StateChanged
        escucha.setEq(2, js2.getValue());
    }//GEN-LAST:event_js2StateChanged

    private void js9StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_js9StateChanged
        escucha.setEq(8, js9.getValue());
    }//GEN-LAST:event_js9StateChanged

    private void js7StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_js7StateChanged
        escucha.setEq(7, js7.getValue());
    }//GEN-LAST:event_js7StateChanged

    private void jPanel12KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel12KeyPressed
       
        setFocusable(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel12KeyPressed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       valores();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(uiEqualizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(uiEqualizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(uiEqualizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(uiEqualizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                uiEqualizador dialog = new uiEqualizador();
                dialog.setVisible(true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider Parlante;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider js0;
    private javax.swing.JSlider js1;
    private javax.swing.JSlider js2;
    private javax.swing.JSlider js3;
    private javax.swing.JSlider js4;
    private javax.swing.JSlider js5;
    private javax.swing.JSlider js6;
    private javax.swing.JSlider js7;
    private javax.swing.JSlider js8;
    private javax.swing.JSlider js9;
    // End of variables declaration//GEN-END:variables
  public void cargarSlider()
    {
        eq1=new JSlider[]{js0,js1,js2,js3,js4,js5,js6,js7,js8,js9};
       
 
    }
 public void valores() {
    
     cargarSlider();
    equalAudio.cargarOpciones(jComboBox1.getSelectedIndex(), eq1);
    if(escucha!=null)        
    {for(int i=0;i<eq1.length;i++)
            {
                
            escucha.setEq(i, eq1[i].getValue());
            }
          
        
           }
 }
 
 public void cambiarDiseñoSlider(){
 js0.setUI(new DibujarBordes().getSliderUI(js0));
 }
   

}
